apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../postgres

patches:
  - path: replicas.yaml

images:
  - name: ghcr.io/rainzler-exagone/flowforge-api
    newTag: eb4bb80f56f69683f7dcb41ec02546725477d568

  - name: ghcr.io/rainzler-exagone/flowforge-worker
    newTag: eb4bb80f56f69683f7dcb41ec02546725477d568