apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas.yaml

images:
  - name: ghcr.io/rainzler-exagone/flowforge-api
    newTag: API_IMAGE_TAG

  - name: ghcr.io/rainzler-exagone/flowforge-worker
    newTag: WORKER_IMAGE_TAG