apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../postgres/deployment.yaml
  - ../../../postgres/service.yaml
  - ../../../postgres/pvc.yaml

patches:
  - path: replicas.yaml

images:
  - name: ghcr.io/rainzler-exagone/flowforge-api
    newTag: adc700314b9fcdad1df15eca3b18c9b3bf903a0a

  - name: ghcr.io/rainzler-exagone/flowforge-worker
    newTag: adc700314b9fcdad1df15eca3b18c9b3bf903a0a