apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - kafka-deployment.yaml
  - kafka-service.yaml

  - vault-connection.yaml
  - vault-auth.yaml
  - vault-static-secrets.yaml
