apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: flowforge-postgres-secret
  namespace: flowforge
spec:
  type: kv-v2

  mount: secret
  path: flowforge/postgres

  destination:
    name: flowforge-database-secret
    create: true
    overwrite: true

  vaultAuthRef: flowforge-vault-auth